[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
diesel = { version = "2.2.4", features = [
  "sqlite",
  "returning_clauses_for_sqlite_3_35",
  "chrono",
] }
chrono = "0.4.38"
